# coding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Use the standard xenial base box for all VMs.
  config.vm.box = "ubuntu/xenial64"

  # Disable update checks – we don't want people to redownload boxes
  config.vm.box_check_update = false

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"

    # Downloads speeds within VMs are horrendous without these.
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
    vb.customize ["modifyvm", :id, "--uartmode1", "disconnected"]
  end

  # The VM for all stateful services (MongoDB, MySQL, Redis, etc.)
  # We want the provisioner for this to run first, so the services are available to the platform.
  config.vm.define "services" do |services|
    services.vm.box = "smarnach/edx-services"
    services.vm.hostname = "services"
    services.vm.network "private_network", ip: "192.168.33.11"
  end

  # The VM for edx-platform
  config.vm.define "platform", primary: true do |platform|
    platform.vm.box = "smarnach/edx-platform"
    platform.vm.hostname = "platform"
    platform.vm.network "private_network", ip: "192.168.33.10"
    platform.vm.network "forwarded_port", guest: 8000, host: 8000
    platform.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
    end
  end
end
